spring:
  h2: #기존에 적었던 코드네요. 참고로, devtools 라이브러리 설치시, 이 3줄은 안 적어도 됨
    console:
      enabled: true

  # 여러줄 주석처리 : 전체 드래그후, ctrl /
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/jpashop
  #    usersname: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  #
  jpa:
    hibernate:
      ddl-auto: create # 영구 디비를 원할 시, none
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

